### ISSUE TITLE
HelpDAO template parameters

### ISSUE THREAD

**Issue by luisivan** [helpdao/dao-template#1]
I propose the following parameters:
- 66% support, 33% minimum acceptance and 7 days duration for donors to add/remove supervisors
- 80% support, 50% minimum acceptance and 1 day for:
  - Supervisors to add/remove other supervisors
  - Supervisors to add/remove volunteers
  - Supervisors to approve finance requests from volunteers

That means that if there are 100 donors, at least 22 should vote yes and no more than 11 should vote no in order for the proposal to pass.
And if there are 10 supervisors, at least 4 should vote yes and no more than 1 should vote no for the proposal to pass.

Do this parameters sound like a sensible default?

**Comment by AaronAbuUsama** [comment]
> Do this parameters sound like a sensible default?

Higher supports makes sense, 50% Quorum & 1day vote duration is fine but means we need high co-ordination amongst supervisors

**Comment by enriquegasch** [comment]
It was me who proposed the option of positivism in the search of acurated consensus.

The default makes donators, feel more safe about their donations.

But we have no time to loose and a system of approved steps with 48 hours marging first and 24 hours marging thereafter makes more sense to me.

**Comment by luisivan** [comment]
> > Do this parameters sound like a sensible default?
> 
> Higher supports makes sense, 50% Quorum & 1day vote duration is fine but means we need high co-ordination amongst supervisors

Exactly, I think that is fine.
